name: Testing GITHUB ACTIONS.

on:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo : "This works just fine!"
